kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rolebinding-ns1-bob
  namespace: ns1
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: sso:bob-tkg-dev@vsphere.local
  apiGroup: rbac.authorization.k8s.io

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rolebinding-ns1-bob-psp
  namespace: ns1
roleRef:
  kind: ClusterRole
  name: psp:vmware-system-restricted
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: sso:bob-tkg-dev@vsphere.local
  apiGroup: rbac.authorization.k8s.io

