apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: ns1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: kubernetes-remote-storage
  resources:
    requests:
        storage: 2Gi
